# Generated by Django 4.0.6 on 2022-07-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flakon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('capacity', models.FloatField()),
                ('image', models.ImageField(upload_to='flakon')),
            ],
        ),
    ]
